FROM python:3.11-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev libgeos-dev libproj-dev gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml README.md ./
COPY wced/ wced/
RUN pip install --no-cache-dir "."

COPY data/ data/
COPY alembic.ini ./

CMD ["prefect", "worker", "start", "--pool", "wced-pool", "--type", "process"]
