FROM python:3.11-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev libgeos-dev libproj-dev gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml README.md ./
COPY wced/ wced/
RUN pip install --no-cache-dir ".[api]"

COPY data/ data/
COPY alembic.ini ./

EXPOSE 8000

CMD ["uvicorn", "wced.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
